### ISSUE TITLE
Reduce MAX_DEPTH to speed up regression finding

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#129]
Depends on #115, as we need to make sure we don't worsen our regression detection rate.

**Comment by ahal** [comment]
Would this actually speed things up substantially? The first push would be faster since we load fewer than 28 pushes around it. But after that, we only load one additional parent push each time (due to caching). There's definitely some computational overhead, but I wonder if less accurate regression detection would be worth the speed up.

That said maybe we could lower it to 10 to match the backstop without sacrificing accuracy.

**Comment by marco-c** [comment]
We're now skipping pushes which were not backed out nor bustage fixed, so this could also help when there is a large enough distance between two possibly "bad" pushes.
It shouldn't be a big win anyway because it's not so frequent and after we fix the last caching issues (#86 and https://github.com/mozilla/adr/issues/79).

**Comment by marco-c** [comment]
Yeah, I guess it's not that useful.
