### ISSUE TITLE
Support WPT groups

### ISSUE THREAD

**Issue by ahal** [mozilla/mozci#153]
Now that WPT groups are being propagated to ActiveData, mozci needs to handle them.

This involves:
* Updating the integration tests
* Updating the `is_bad_manifest` check in task.py
* ???

**Comment by marco-c** [comment]
The first part is in #156.
Here's what's left:
- check if the harness could return full relative paths, so we have the same behavior as the other suites;
- wait for @ekyle to fix an issue in ActiveData which is preventing result groups for WPT to be injested;
- wait a couple of days before updating `test_missing_manifests` and `test_missing_result_manifests` (since those queries get data from the past 2 days, we need to wait 2 days since the introduction of groups in WPT).
