### ISSUE TITLE
Drop `kind` from queries and from the Task class

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#44]
We are not using it. @ahal do you remember why you added it? Were you planning on using it somehow?

**Comment by ahal** [comment]
I think it was only used to determine whether it is a `test` task or not, but that could come from the label as well. Maybe it is already.

At the time, I likely added it because it was available and I thought it might be something useful in the future. We can drop it for now if it's making things slower.

**Comment by marco-c** [comment]
I was thinking of removing it simply because it is not currently used and it's the only field for which we have no fallback (https://github.com/mozilla/mozci/blob/64ab67acae353051005146123604d85cb76006f7/mozci/push.py#L205).

**Comment by marco-c** [comment]
This has been removed.
