### ISSUE TITLE
Builds not retrieved from treeherder_db source in v2.0.1

### ISSUE THREAD

**Issue by sarah-clements** [mozilla/mozci#454]
In the 2.0.1 release, something seems to have changed with regards to the `treeherder_db` source that causes build tasks not to be retrieved. The results I see locally (set to ['treeherder_client', 'hgmo', 'taskcluster']) is not the same as what is used in production ['treeherder_db', 'hgmo', 'taskcluster']. I don't see this discrepancy with v2.0.0 (results are the same across primary data sources).

**Comment by marco-c** [comment]
02ce0d515cb70ca6b1e4e204f3b2b187b7f44a89 and 97e96526351df620ad676408dfd34a0ffa4f0152 are the only commits between 2.0.0 and 2.0.1, and they should only affect groups (so nothing should have changed for builds).

Is what you're seeing only affecting `treeherder_db` and not `treeherder_client`?

**Comment by ahal** [comment]
@sarah-clements are you able to test the `treeherder_db` source locally somehow? Would be helpful to have a smaller test case to reproduce, e.g something like:
```python
push = Push("<rev>", "<branch>")
labels = push.get_regressions("label")
assert any(l.startswith("build-") for l in labels)
```

**Comment by sarah-clements** [comment]
I did a lot of testing and it's happening with both sources. I was able to reproduce it locally by pointing to the production replica db (but not local mysql with this push and task ingested). I looked at revision 20109adcd4c678e43da8e63326c4350c45ca7762 which only has one failed build [task](https://treeherder.mozilla.org/jobs?repo=try&resultStatus=testfailed%2Cbusted%2Cexception%2Crunnable&revision=20109adcd4c678e43da8e63326c4350c45ca7762).

Starting with release 1.12.6, I set the local config file set to `['treeherder_db', 'hgmo', 'taskcluster']` and then changed the mozci config back to `['treeherder_client', 'hgmo', 'taskcluster']`, then cleared the cache. From both sources I saw: `['build-linux64/opt']`. I repeated this on v2.0.0 and the results were the same.

Then I tried it on v2.0.1, but with`treeherder_db` and `treeherder_client` I got zero labels. I also saw `Problem retrieving mozci labels for push try 20109adcd4c678e43da8e63326c4350c45ca7762 : test_task_groups`, which is logging I added for when an exception is caught. This happened a few times after clearing the cache and refreshing the page, and then of course, if I refreshed without clearing the cache it didn't show that message (and I still didn't have build results).

**Comment by ahal** [comment]
Thanks Sarah! I can reproduce with:
```
In [1]: from mozci.push import Push
14:53:14.530 | INFO     | mozci.data.base:50  - Sources selected, in order of priority: ('treeherder_client', 'hgmo', 'taskcluster').

In [2]: push = Push("20109adcd4c678e43da8e63326c4350c45ca7762", "try")

In [3]: push.get_likely_regressions("label")
```

Looks like it was regressed by this commit https://github.com/mozilla/mozci/commit/02ce0d515cb70ca6b1e4e204f3b2b187b7f44a89, though I'm still trying to figure out how.. for some reason it is calling into the `test_task_groups` contract even though there are no test tasks in that push..

**Comment by ahal** [comment]
I figured it out, will have a PR up soon.

Turns out https://github.com/mozilla/mozci/commit/97e96526351df620ad676408dfd34a0ffa4f0152 is the regression (not the other one). And it's not really a regression so much as exposing a pre-existing error. Basically the `taskcluster` source returns all tasks that taskgraph knows about. This includes tasks that are unscheduled or have expired with out ever running.

This means it will include test tasks that never ran (e.g due to a failed build like in [20109adc](https://treeherder.mozilla.org/jobs?repo=try&resultStatus=testfailed%2Cbusted%2Cexception%2Crunnable&revision=20109adcd4c678e43da8e63326c4350c45ca7762)). Everytime we call `get_test_task_groups` on such a task, we raise `SourcesNotFound` exception since treeherder doesn't have any data on them. Previously these exceptions were swallowed by the futures module, but as of https://github.com/mozilla/mozci/commit/97e96526351df620ad676408dfd34a0ffa4f0152 we started propagating them back to the main thread which causes `get_likely_regressions` to fail.

Sarah likely never noticed the exception because we log a debug message every time the treeherder data source can't fulfill a task (which in this case was all of them). I had to turn this logging off just to find the exception locally.

**Comment by marco-c** [comment]
> Turns out 97e9652 is the regression (not the other one). And it's not really a regression so much as exposing a pre-existing error. Basically the taskcluster source returns all tasks that taskgraph knows about. This includes tasks that are unscheduled or have expired with out ever running.

One of the cases where running into a regression is welcome :)
