### ISSUE TITLE
Extend the classify command to perform retriggers and backfills when it needs more information

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#534]
The algorithm behind the classify command isn't always able to give a decision between "good" or "bad" and sometimes needs more information in order to be sure.

When a situation like this happens and the `classify` command returns "unknown", it should automatically identify and perform the set of actions (retriggers and/or backfills) that would be necessary to gather enough information.

Depends on https://github.com/mozilla/mozci/issues/504 and https://github.com/mozilla/mozci/issues/508.

**Comment by ahal** [comment]
We'll need to decide how this will work in practice.. Should the `classify` command do the retriggers, then block until the tasks are complete before trying again? Or will it just retrigger them and return so that the next time it gets run the results should be a bit better?

If the latter, then maybe we should implement this behind a separate command (or a flag on the classify command) so that retriggering them is explicit, and can be done only in circumstances we know there will be a benefit.

**Comment by marco-c** [comment]
I'd vote for the latter, it looks easier to implement. We could add a `--retrigger` flag to the classify command.

**Comment by marco-c** [comment]
I've opened #654 for backfills and for choosing the best action between retrigger and backfill.
