### ISSUE TITLE
Add a method to identify if a test failure is a timeout, a crash, or a generic (correctness) failure

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#684]
See the description in https://bugzilla.mozilla.org/show_bug.cgi?id=1758984#c2 on how to do it.

**Comment by La0** [comment]
Each `TestTask` should then have a nullable enum `failure_type`, where choices are:
- `timeout`
- `crash`
- `generic`

As mentionned in the bug description, `timeout` is easy to detect from `errorsummary` (already managed in `ErrorSummarySource`): `status` value on a log line  is different from `expected` value AND `status` is set to `TIMEOUT`

Same idea for `crash`: `signature` field is present and `action` is set to `crash`.

Other failures (that do not match these criterias) are set to `generic`

@marco-c @jmaher Do you want to support the remaining cases from `live.log` here ? They are more involved because Mozci does not support parsing `live.log` now (from what I can tell).

**Comment by marco-c** [comment]
Yes, that's correct.

The property should be assigned to each group (`GroupResult`) rather than each TestTask because in a TestTask there might be multiple tests failing in different ways (same for group actually, but at least in group it should be more rare). To handle the case where there are multiple failures, we can make the property a list (failure types) or a dict (test -> failure type).

Given that it is expensive to load the errorsummary.log file, we should compute this on demand rather than as soon as we create a TestTask instance. So let's add a function to compute it, and we only call the function when we have classified a failure as intermittent to check if we have to filter it out or not.

> @marco-c @jmaher Do you want to support the remaining cases from live.log here ? They are more involved because Mozci does not support parsing live.log now (from what I can tell).

No, we can leave them out.

**Comment by jmaher** [comment]
I think there are other things to consider:
 * assertion
 * leak
 * infra

on timeout, do we care about test timeout or tooling/harness/browser timeout?

**Comment by La0** [comment]
@jmaher Are these listed in `errorsummary.json` or `live.log` ? If it's `live.log` it will be a followup

**Comment by jmaher** [comment]
these are not specific annotations and would require deriving it from `live.log`, so a followup is good

**Comment by jmaher** [comment]
or we edit the harnesses to make `errorsummary.json` more inclusive

**Comment by marco-c** [comment]
I filed #686 about what @jmaher mentioned.

**Comment by La0** [comment]
We discussed the implementation with @EvaBardou and here is what we'll do:

1. add a new data contract named `test_task_failures` implemented solely by `mozci/data/sources/artifact/__init__.py` (we can't use the existing `test_task_errors` as it's not the same output)
2. this new contract will implement the rules described above, by parsing the `errorsummary.log` lines and wil output a dict of `Group => List(FailureType, test path)` so that consumers can retrieve all failures found for each group.
3. a new method named `get_failures` will be added to `GroupResult` that will trigger this contract
4. to trigger the contract, `GroupResult` needs to know its parent task id, so this will passed to the `GroupResult.__init__` from `TestTask` and stored in the `GroupResult` data class
5. a few unit tests will be provided to validate the behaviour of `get_failures` using mocks of `errorsummary.log`

**Comment by marco-c** [comment]
We could avoid storing the task id in GroupResult if we define `get_failures` in TestTask instead

**Comment by EvaBardou** [comment]
> We could avoid storing the task id in GroupResult if we define `get_failures` in TestTask instead

You're right, but, earlier, you said :
> The property should be assigned to each group (GroupResult) rather than each TestTask because in a TestTask there might be multiple tests failing in different ways (same for group actually, but at least in group it should be more rare).

So we were planning on adding the function to `GroupResult`, if it isn't necessary anymore please tell me and I will add it to `TestTask` instead!
