### ISSUE TITLE
Cache task groups and results

### ISSUE THREAD

**Issue by marco-c** [mozilla/mozci#86]
When data is missing from ActiveData, we retrieve it from Taskcluster. We memoize it, but don't cache it, which means we have to get it again if we re-run.

**Comment by armenzg** [comment]
Conversation between marco and I.

**marco**: I'd cache what we get as a fallback when these two adr queries fail https://github.com/mozilla/mozci/blob/4666f787a0e06e55febde3723a5c9a586fb32856/mozci/push.py#L215-L223
that is, mainly these https://github.com/mozilla/mozci/blob/4666f787a0e06e55febde3723a5c9a586fb32856/mozci/task.py#L132-L134
right now, rerunning Push.tasks is very fast when the data is available in AD (12 weeks), as ADR caches the AD query results; it is very slow when the data is not available in AD (older than 12 weeks)

**me**: Is there a specific test that tests this scenario? Should I be trying to get the integration tests running locally?

**marco**: not yet, but you could possibly adapt https://github.com/mozilla/mozci/pull/74/files to test that scenario. You just need to get an old push (e.g. from 5 months ago), and then get its tasks

**me**: Why do we query ADR instead of Taskcluster for tasks? I have some code to fetch tasks in here https://github.com/mozilla/treeherder/blob/master/treeherder/etl/management/commands/ingest.py#L85-L99

**marco**: we query AD, fallback on Taskcluster. Querying AD is faster, as when we fallback on Taskcluster we have to load a lot of artifacts

**me**: let me see if I follow
recent pushes will fail because AD is not yet caught up
less recent pushes are faster on AD than TC
is that so far good context?
you mention old pushes (e.g. 5 months); what's special about old pushes?

**marco**: AD only has data for less recent pushes
in the unittest table up to 12 weeks
so for old pushes, we have to fallback to Taskcluster too

**me**: You mention in the issue that when data is missing from ActiveData we then fetch it from Taskcluster, however, I only see AD queries executed in the code you pointed out https://github.com/mozilla/mozci/blob/4666f787a0e06e55febde3723a5c9a586fb32856/mozci/push.py#L215-L223. When do we fetch from Taskcluster?

**marco**: when we access these properties of a task: https://github.com/mozilla/mozci/blob/4666f787a0e06e55febde3723a5c9a586fb32856/mozci/task.py#L200-L216
